version: '3.8'

services:
  # -------------------------------------------------------------
  # CORE API GATEWAY
  # -------------------------------------------------------------
  sentinel_api:
    image: shriramrajat/sentinelstack:v1
    container_name: sentinel_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    networks:
      - sentinel_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "alembic upgrade head && 
             uvicorn sentinelstack.gateway.main:app --host 0.0.0.0 --port 8000"

  # -------------------------------------------------------------
  # DATABASE (Postgres)
  # -------------------------------------------------------------
  db:
    image: postgres:15-alpine
    container_name: sentinel_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - sentinel_net

  # -------------------------------------------------------------
  # CACHE (Redis)
  # -------------------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: sentinel_redis
    restart: always
    volumes:
      - redis_data_prod:/data
    networks:
      - sentinel_net

  # -------------------------------------------------------------
  # MONITORING (Prometheus)
  # -------------------------------------------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: sentinel_prometheus
    restart: always
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090" # Expose Prometheus UI
    networks:
      - sentinel_net

  # -------------------------------------------------------------
  # VISUALIZATION (Grafana)
  # -------------------------------------------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: sentinel_grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000" # Expose Grafana UI (Changed to avoid conflict)
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - sentinel_net

volumes:
  postgres_data_prod:
  redis_data_prod:
  prometheus_data:
  grafana_data:


networks:
  sentinel_net:
    driver: bridge
