global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sentinelstack_prod'
    scrape_interval: 5s
    static_configs:
      - targets: ['sentinel_api:8000'] 
      # 'sentinel_api' matches the service name and container_name in docker-compose